services:
  - type: web
    name: logs-web
    env: php
    plan: free
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_KEY
        value: base64:30lXYAojVz0d2xLrsCAqQ547Q00nxGQGnT5CN5drvgw=
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /tmp/database.sqlite